mkdir -p User
mkdir -p Nurse
mkdir -p Certification
mkdir -p NurseCertification
mkdir -p Specialization
mkdir -p WorkDay
mkdir -p Client
mkdir -p Medication
mkdir -p ClientMedication
mkdir -p Driver
mkdir -p Item
mkdir -p Document
mkdir -p PreviousClient
mkdir -p Note
mkdir -p Task
mkdir -p HourlyData
mkdir -p AssessmentInfo
mkdir -p ClientNurseHistory
mkdir -p NurseSpecialization
mkdir -p NurseWorkDay
mkdir -p AssignedNurse
mkdir -p AssignedDriver
